Fix Overview page to convey general idea of project
tremor-rs/tremor-www pull request #84
Opened 2021-09-28 04:52 UTC by bchen28

The main purpose of the Overview page should be giving new users a general idea of what the Tremor project is and what it can be used for. According the Tech Assessments Doc written by Celeste Horgon, I hope to coalesce general information onto this page from the original Architecture Overview page and the About us page to give users a more well-rounded idea of what Tremor is. Moving forward, I want to suggest a cross-section of documentation hierarchy that will allow for easier cross-navigation between pages and understanding of essential terms. 
- Docs 
    - Overview 
    - Model 
        - Onramps
        - Offramps
        - Pipeline
        - Codecs
    - etc. 

I've left most of the more esoteric model information in this page for now, but my next step will be removing that material into separate pages and subsections.

2021-09-28 07:20 UTC, darach commented
The terms `onramp` and `offramp` are legacy terms. We are transitioning to the terms `source`, `sink` and `connector` here as they are more general terms. The `connector` branch ( and related RFC ) is a work in progress but the legacy terms will be written out of documentation in the next ( v0.12 ) release of the project.

2021-09-28 07:21 UTC, darach approved these changes
LGTM 👍

2021-09-28 07:24 UTC, skoech commented on docs/overview.md
> +- Event processing - Tremor adopts principles from the Distributed Event Based Systems, Event Stream Processor (ESP) and Complex Event Processing (CEP) communities; however, it currently encompasses
You might want to add the 'DEBS' abbreviation like for the others here.

2021-09-28 07:38 UTC, skoech commented on docs/overview.md
> +The API in turn interfaces with registry and repository facilities. Tremor distinguishes between artefacts and instances. artefacts in Tremor have no runtime overhead.
Not sure why you changed the case for 'Artefacts' here.

2021-09-28 07:40 UTC, skoech commented on docs/overview.md
> +Artefacts can be thought of analagous to code. They are a set of instructions, rules or configurations. As such they are registered with Tremor via its API and stored in Tremor's artefact repository.
How about "Artefacts can be thought of as analagous to code."?

2021-09-28 07:42 UTC, skoech commented on docs/overview.md
>  Deployment in Tremor, is achieved through a mapping artefact. The mapping artefact specifies how artefacts should be deployed into one or many runtime instances, activated, and connected to live inst
"Deployment in Tremor is achieved through a mapping artefact." No need for the comma, right? :D

2021-09-28 07:46 UTC, skoech requested changes
Again, absolutely brilliant. Brief and direct in a refreshing way. Maybe just a few changes I thought you could go over.

2021-09-30 06:48 UTC, bchen28 commented
I turned this into a rather exhaustive content overhaul of what preexisted in the Overview page. No content was moved elsewhere, existing information was simply consolidated, reorganized, and rewritten to provide a more concise and user-friendly understanding of the project. I'm too tired and it's a bit late in the night for me to comment on specific questions I had regarding wording and technical accuracy, but I can link those tomorrow. Would appreciate any thoughts/comments @skoech @darach @Licenser

2021-09-30 09:25 UTC, skoech commented on docs/overview.md
> +- Event processing - Tremor's primary goal is to operate as an Extract, Transform, and Loading (ETL) tool. While Tremor adopts principles from Distributed Event Based Systems (DEBS), Event Stream Pro
This is a great synopsis of how @darach explained the Tremor architecture and functionality yesterday. But, I was thinking maybe we should maintain the element of possibility here. Like, "It's currently not exhaustive..." or, "It is by no means an exhaustive system... yet...". Something along those lines. What do you think?

2021-09-30 09:39 UTC, skoech commented on docs/overview.md
> +The current configuration model uses a shorthand URL form. It discriminates artefacts by type, so it is often sufficient to infer the `tremor:///{artefact-kind}` component when specifying configuring
... specifying or configuring artefacts.

2021-09-30 09:43 UTC, skoech commented on docs/overview.md
> +For bindings, full URL path components are needed (ie.:`/pipeline/01`).
I think e.g. is more appropriate here.

2021-09-30 09:45 UTC, skoech commented on docs/overview.md
> +In pipelines, events are processed in depth first order. In cases where Tremor operators have no intrinsic ordering (such as a branch split), Tremor internally _imposes_ an order.
depth-first

2021-09-30 09:52 UTC, skoech commented on docs/overview.md
> +- Bindings - a specefic configuration of how all other artefacts should be connected
specific*

2021-09-30 09:59 UTC, skoech commented on docs/overview.md
> +Tremor does not yet have an out-of-the-box network protocol. A native Tremor protocol is planned for development in the immediate/mid-term.
I think medium-term is more appropriate as it references a  period of time in the near future.

2021-09-30 10:07 UTC, skoech approved these changes
Looks great to me. 👍🏿

2021-09-30 10:48 UTC, Licenser approved these changes
re apprive since update unapproved

2021-09-30 10:55 UTC, merged